name: "Pre-merge Quality-Control"
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"

    strategy:
      matrix:
        pg_version: ["11", "12", "13", "14", "15"]

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.pgx
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-pg${{ matrix.pg_version }}

      - name: Init pgx
        run: |
          cargo install cargo-pgx --version 0.7.4
          cargo pgx init --pg${{ matrix.pg_version }}=download

      - name: Run testsuite
        run: |
          cargo pgx test --features pg${{ matrix.pg_version }} pg${{ matrix.pg_version }}

  qc:
    runs-on: ubuntu-latest
    name: "Quality Control"

    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.pgx
            target/
          key: ${{ runner.os }}-${{ steps.rust-install.outputs.cachekey }}-pg15

      - name: Init pgx
        run: |
          cargo install cargo-pgx --version 0.7.4
          cargo pgx init --pg15=download

      - name: Check formatting
        run: |
          cargo fmt --check

      - name: Consult Clippy
        run: |
          cargo clippy --features=pg15 -- -D warnings
